g_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path,re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.log_in, name='login'),
    path('logout/',views.log_out, name='logout'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('register/',views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    path('accounts/password_reset/',auth_views.password_reset,name='password_reset'),
    path('accounts/password_reset/done/',auth_views.password_reset_done,name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.password_reset_confirm,name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.password_reset_complete,name='password_reset_complete'),
    path('password/',views.change_password, name='change_password'),
    path('dashboard/vote/<int:question_id>/', views.vote, name='vote'),
    path('dashboard/mypolls/',views.mypolls, name='mypolls'),
    path('dashboard/createpolls/',views.createpolls, name='createpolls'),
    path('dashboard/createchoice/<int:question_id>',views.createchoice, name='createchoice'),
    path('dashboard/editpoll/<int:question_id>',views.editpoll, name='editpoll'),
    path('dashboard/editchoice/<int:choice_id>',views.editchoice, name='editchoice'),
    path('dashboard/deletepoll/<int:question_id>',views.deletepoll, name='deletepoll'),
    path('dashboard/deletechoice/<int:choice_id>',views.deletechoice, name='deletechoice'),
    path('dashboard/mypolls/chart/<int:question_id>',views.chart, name='chart'),
    path('dashboard/mypolls/chart/data/<int:question_id>',views.chartdata, name='chartdata'),
    path('dashboard/surveys/',views.surveys, name='surveys'),
    path('dashboard/mysurveys',views.mysurveys, name='mysurveys'),
    path('dashboard/mysurveys/createsurveys/<int:question_count>',views.createsurveys, name='createsurveys'),
    path('dashboard/mysurveys/editsurvey/<int:title_id>',views.editsurvey, name='editsurvey'),
    path('dashboard/mysurveys/deletesurvey/<int:title_id>',views.deletesurvey, name='deletesurvey'),
    path('dashboard/surveys/surveyresponse/<int:title_id>',views.surveyresponse, name='surveyresponse'),
    path('dashboard/mysurveys/showresponders/<int:title_id>',views.showresponders, name='showresponders'),
    path('dashboard/mysurveys/showresponders/showresponse/<username>/<int:title_id>',views.showresponse, name='showresponse'),
]

polls/models.py
from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User

import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    username = models.ForeignKey(User, on_delete=models.CASCADE)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Votes(models.Model):
    username = models.CharField(max_length=20)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.username

class Surveytitle(models.Model):
    title = models.CharField(max_length=100)
    modified = models.DateTimeField('date modified')
    responses = models.IntegerField(default=0)
    username = models.ForeignKey(User,on_delete=models.CASCADE)

    def was_modified_recently(self):
        return self.modified >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.title

class Surveyquestion(models.Model):
    title = models.ForeignKey(Surveytitle,on_delete=models.CASCADE,null=True)
    question = models.CharField(max_length=200)
    username = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.question

class Surveyanswer(models.Model):
    title = models.ForeignKey(Surveytitle,on_delete=models.CASCADE,null=True)
    question = models.ForeignKey(Surveyquestion,on_delete=models.CASCADE)
    answer = models.TextField()
    username = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

polls/forms.py
from django import forms
import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class PollForm(forms.Form):
    question_text = forms.CharField(max_length =200)
    pub_date = forms.DateTimeField(initial=datetime.datetime.now())

class PollChoiceForm(forms.Form):
    choice_text = forms.CharField(max_length=200)

class SurveyForm(forms.Form):
    question = forms.CharField(widget=forms.TextInput(attrs={'required' : 'required'}),max_length =200)
    answer = forms.CharField(widget=forms.Textarea(attrs={'readonly' : 'readonly'}),required=False)

class SurveyResponseForm(forms.Form):
    question = forms.CharField(widget=forms.TextInput(attrs={'required' : 'required','readonly' : 'readonly'}),max_length =200)
    answer = forms.CharField(widget=forms.Textarea(attrs={'required' : 'required'}))

class ViewSurveyForm(forms.Form):
    question = forms.CharField(widget=forms.TextInput(attrs={'readonly' : 'readonly'}))
    answer = forms.CharField(widget=forms.Textarea(attrs={'readonly' : 'readonly'}))

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .models import Question, Choice, Votes, Surveytitle, Surveyquestion, Surveyanswer

from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm

from django.contrib.auth import login, authenticate,logout,update_session_auth_hash

from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm,PollForm,PollChoiceForm,SurveyForm,SurveyResponseForm, ViewSurveyForm, SignupForm

from django.contrib.auth.models import User

from django.urls import reverse

from django.forms import formset_factory,BaseFormSet

from django.contrib import messages

from django.conf import settings

from django.template.loader import render_to_string

from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes, force_text

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .tokens import account_activation_token

from django.core.mail import EmailMessage

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import datetime

import requests


def home(request):
    if request.user.is_authenticated:
        return redirect('polls:dashboard')
    
    return render(request, 'polls/home.html')

def log_in(request):
    if request.user.is_authenticated:
        return redirect('polls:dashboard')
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('polls:dashboard')
            else:
                return render(request,'polls/login.html',{'form' : form,'user' : user})
    else:
        form = UserLoginForm
    context = { 'form' : form }
    return render(request,'polls/login.html', context)


def log_out(request):
    logout(request)
    return redirect('polls:home')


def register(request):
    if request.user.is_authenticated:
        return redirect('polls:dashboard')
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()

            if result['success']:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('polls/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                    'token':account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                return HttpResponse('An activation Link has been sent to your email address.Please Check your Inbox')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = SignupForm()

    context = { 'form' : form }
    return render(request, 'polls/register.html', context)


def activate(request, uidb64, token,backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Thank you for your email confirmation. Now you have logged In')
        return redirect('polls:dashboard')
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('polls:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'polls/change_password.html', {'form': form})


@login_required(login_url='/login')
def dashboard(request):
    username = request.user
    latest_question_list = Question.objects.exclude(username = username)
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/dashboard.html',context)

@login_required(login_url='/login')
def vote(request,question_id):
    username = request.user
    latest_question_list = Question.objects.exclude(username = username)
    question = get_object_or_404(Question, pk=question_id)
    try:
        voted_question = Votes.objects.get(username = username,question_text = question)
    except Votes.DoesNotExist:
        voted_question = None
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/dashboard.html', {
            'latest_question_list': latest_question_list,
            'error_message': "You didn't select a choice.",
        })
    else:
        if voted_question == None: 
            selected_choice.votes += 1
            selected_choice.save()
            u = Votes(username = username,question_text = question)
            u.save()
            return render(request, 'polls/dashboard.html',{'latest_question_list': latest_question_list,'selected_choice' : selected_choice})
        else:
            return render(request, 'polls/dashboard.html', {
                'latest_question_list': latest_question_list,
                'error_message': "You have already voted for that question",
                })

@login_required(login_url='/login')
def mypolls(request):
    username = request.user
    latest_question_list = Question.objects.filter(username = username)
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/mypolls.html',context)

@login_required(login_url='/login')
def createpolls(request):
    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            username = request.user
            question = username.question_set.create(question_text=request.POST['question_text'],pub_date=request.POST['pub_date'])
            return redirect('polls:mypolls')
    else:
        form = PollForm()
    username = request.user
    latest_question_list = Question.objects.filter(username = username)
    context = { 'form' : form,'latest_question_list': latest_question_list }
    return render(request,'polls/createpolls.html', context)

@login_required(login_url='/login')
def createchoice(request,question_id):
    if request.method == 'POST':
        form = PollChoiceForm(request.POST)
        if form.is_valid():
            question = get_object_or_404(Question, pk=question_id)
            choice = question.choice_set.create(choice_text=request.POST['choice_text'])
            question.choice_set.update(votes =0)
            vote = Votes.objects.filter(question_text= question.question_text)
            vote.delete()
            return redirect('polls:mypolls')
    else:
        form = PollChoiceForm()
    question = get_object_or_404(Question, pk=question_id)
    context = { 'form' : form,'question' : question}
    return render(request,'polls/createchoice.html', context)

@login_required(login_url='/login')
def editpoll(request,question_id):
    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            question = get_object_or_404(Question,pk=question_id)
            question.question_text = request.POST['question_text']
            question.pub_date = request.POST['pub_date']
            question.save()
            question.choice_set.update(votes =0)
            vote = Votes.objects.filter(question_text= question.question_text)
            vote.delete()
            return redirect('polls:mypolls')
    else:
        question = get_object_or_404(Question,pk=question_id)
        data={'question_text' : question.question_text,'pub_date' : question.pub_date}
        form = PollForm(data)

    context = { 'form' : form, 'question' : question }
    return render(request,'polls/editpoll.html', context)

@login_required(login_url='/login')
def editchoice(request,choice_id):
    if request.method == 'POST':
        form = PollChoiceForm(request.POST)
        if form.is_valid():
            choice = get_object_or_404(Choice,pk=choice_id)
            choice.choice_text = request.POST['choice_text']
            choice.votes = 0
            choice.save()
            question = choice.question

polls/templates/polls/chart.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script>
var endpoint = "{% url 'polls:chartdata' question_id %}" 
var defaultData= []
var labels = []
$(document).ready(function(){
    $.ajax({ 
        method: "GET",
        url: endpoint,
        success: function(data){
            labels = data.labels
            defaultData = data.default
            setchart()
        // console.log(data.customers * 234)
        },  
        error: function(error_data){
            console.log(error);
            console.log(error_data);
        }
    });
function setchart(){
    var ctx = document.getElementById("myChart").getContext('2d');
    var ctx2 = document.getElementById("myChart2").getContext('2d');
    var myChart = new Chart(ctx2, {
        type: 'polarArea',
        data: {
            labels: labels,
            datasets: [{
                label: '# of Votes',
                data: defaultData,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: '# of Votes',
                data: defaultData,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });
}
});             
</script>
</head>
<body>
<h1>STATS</h1>
<div class="col-sm-6">
<canvas id="myChart" width="400" height="400"></canvas>
</div>
<div class="col-sm-6">
<canvas id="myChart2" width="400" height="400"></canvas>
</div>
</body>
</html>

polls/templates/polls/createpolls.html
{% load bootstrap4 %}   
        <div class="modal-dialog">
            <div class="modal-content">
                 <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">CREATE POLLS</h4>
                </div>
                 <div class="modal-body">
                     <form id="form1" method="POST" action ="{% url 'polls:createpolls' %}">
                             {% csrf_token %}
                             <table>
                            {% bootstrap_form form %}
                             </table>
                 <div class="modal-footer">
                        <button onclick="myfunc()" id="formsubmit" type="submit" class="btn btn-primary">CREATE</button>
                    </form>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    

polls/templates/polls/dashboard.html
{% extends 'polls/dashboardlayout.html' %}
{% block content %}
<div class="container">
     {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
<!-- {% if user.is_authenticated %}
<h3 align="right"> Logged In: {{ user.username }} </h3>
{% else %}
<h3> You are not logged in </h3>
{% endif %} -->
{% if latest_question_list %}
<br><br>
<div class="jumbotron">
<h3><u>DISCOVER POLLS</u></h3>
<div class="container">
{% if selected_choice %}<h1>You have voted for&nbsp;&nbsp;<u>{{selected_choice.choice_text}}</u></h1>{% endif %} 
{% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
<br>
    <ol>
    {% for question in latest_question_list %}
    <li><h4>{{ question.question_text }}</h4>
    <br>
    <a href="{% url 'polls:chart' question.id %}" class="btn-primary">CURRENT STATS</a>
    <br><br><br>
    <ul>
        <form id="voteform" action="{% url 'polls:vote' question.id %}"  method="POST">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
            {% endfor %}
            <br>
            <input type="submit" value="Vote"/>
        </form>
    </ul>
    {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
</div>
</div>
{% endblock %}

polls/templates/polls/editchoice.html
<div class="modal-dialog">
        <div class="modal-content">
             <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">CREATE POLLS</h4>
                </div>
             <div class="modal-body">
                 <form method="POST" action ="{% url 'polls:editchoice' choice.id %}" >
                         {% csrf_token %}
                         {{ form.as_p }}
                         <div class="modal-footer">
                         <button type="submit" class="btn btn-primary">EDIT</button>
                    </form>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

polls/templates/polls/editpoll.html
{% load bootstrap4 %}
<div class="modal-dialog">
        <div class="modal-content">
             <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">EDIT POLL</h4>
                </div>
             <div class="modal-body">
                 <form method="POST" action ="{% url 'polls:editpoll' question.id %}" >
                     {% csrf_token %}
                     <table>
                        {% bootstrap_form form %}
                        </table>
                        <br>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">EDIT</button>
                        </form>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    

polls/templates/polls/editsurvey.html
{% load bootstrap4 %}
<div class="modal-dialog">
        <div class="modal-content">
             <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">EDIT SURVEY</h4>
            </div>
             <div class="modal-body">
                <form id="editform" method="POST" action="{% url 'polls:editsurvey' title_id %}">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" required="required" value="{{ title.title }}" class="form-control" placeholder="Title" maxlength="100" id="id_title">
                    <br>
                    <label for="id_pub_date">Publication date:</label>
                    <input type="text" name="pub_date" value="{{ date }}" required="required" class="form-control" placeholder="Publication Date" id="id_pub_date">
                    <br>
                    {% for form in formset %}
                    {% bootstrap_form form %}
                    {% endfor %}
                    <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">EDIT</button>
                </form>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

polls/templates/polls/home.html
{% extends 'polls/layout.html' %}
{% block content %}
{% load staticfiles %}
<body style="background-color:#474e5d;">
	<style>
h1 {
    color: white;
    text-align: center;
}
p {
    color: white;
    text-align: center;
} 
.bg-1 { 
       background-color: #1abc9c; /* Green */
        color: #ffffff;
    }
    .bg-2 { 
      background-color: #474e5d; /* Dark Blue */
      color: #ffffff;
  }
.container-fluid {
    padding-top: 70px;
    padding-bottom: 70px;
}    
</style>
<div class="container-fluid bg-1 text-center">
        <h1 class="cover-heading">Welcome!</h1>
        <p class="lead">Let us help you make smarter decisions today.</p>
        <p class="lead">
          <a href="{% url 'polls:register' %}" class="btn btn-primary">Start today!</a>
        </p>
  </div>
  <div class="container-fluid bg-2 text-center">
  <h3>Already Signed Up?</h3>
  <p class="lead">
          <a href="{% url 'polls:login' %}" class="btn btn-primary">Click here!</a>
        </p>
</div>

{% endblock %}

polls/templates/polls/login.html
{% extends 'polls/layout.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
<div class="jumbotron">
<div class="container">
{% if user == None %}
{% bootstrap_alert "Your username and password didn't match." alert_type='error' dismissable=True %}
{% endif %}
  <h2>Login</h2>
  <br>
  <form method="POST" action ="{% url 'polls:login' %}" >
    <div class="form-group">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
    <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
<br>
<a href= "{% url 'polls:register' %}">Not yet registered?Sign Up</a>
<br><br>
<a href= "{% url 'polls:password_reset' %}">Forgot your password?</a>
    </div>
  </form>
</div></div>
</div>
{% endblock %}

polls/templates/polls/showresponse.html
{% load bootstrap4 %}
<div class="modal-dialog">
        <div class="modal-content">
             <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">RESPONSE FORM</h4>
            </div>
             <div class="modal-body">
                <form id="showform" >
                    {% csrf_token %}
                    {{ formset.management_form }}
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" required="required" readonly="readonly" value="{{ title.title }}" class="form-control" placeholder="Title" maxlength="100" id="id_title">
                    <br>
                    <input type="hidden" name="pub_date" value="{{ date }}" required="required" class="form-control" placeholder="Publication Date" id="id_pub_date">
                    {% for form in formset %}
                    {% bootstrap_form form %}
                    {% endfor %}
                    <div class="modal-footer">
                </form>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

polls/templates/polls/surveyslayout.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
    $(document).ready(function(){
        $("#surveybutton").click(function(){
            var question_count = prompt("How many Questions do you need in your Survey Form?");
            if (question_count == ""){
                location.reload()
            }
            else if(question_count){
                var url = "{% url 'polls:createsurveys' 1234 %}".replace(/1234/, question_count.toString());
                $("#surveyModal").load(url);
            }
            else{
                location.reload();
            }
         });
        });
    </script>
    <script>
    function editsurveyfunc(title_id){
        var url = "{% url 'polls:editsurvey' 1234 %}".replace(/1234/, title_id.toString());
        $("#surveyeditModal").load(url);
    }
    </script>
     <script>
     function responsesurveyfunc(title_id){
         var url = "{% url 'polls:surveyresponse' 1234 %}".replace(/1234/, title_id.toString());
         $("#surveyresponseModal").load(url);
        }
    </script>
    <script>
    function showresponsefunc(username,title_id){
        var url = "{% url 'polls:showresponse' 1234 2345 %}".replace(/1234/,username);
        var fullurl = url.replace(/2345/,title_id.toString())
        $("#showresponseModal").load(fullurl);
        }
    </script>
    <style>
            .btn-primary {
                background: #4285f4;
                border: 1px solid #1266f1;
                color: #ffffff;
                font-family: 'Open Sans', sans-serif;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: 0.23px;
                padding: 12px 32px;
                text-align: center;
                text-decoration: none;
                text-transform: uppercase;
    </style>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
        {% include 'polls/includes/dashboardheader.html' %}
        {% block content %}
        {% endblock %}
    </body>
</html>

polls/templates/polls/vote.html
{% extends 'polls/dashboardlayout.html' %}
{% block content %}
<h1>You have voted for <u>{{choice.choice_text}}</u></h1> 
<a href="{% url 'polls:dashboard' %}">Vote again?</a>
{% endblock %}